import os
import smtplib
from email.mime.text import MIMEText

# Required environment variables:
#   EMAIL_ADDRESS       - your Gmail address (the sender)
#   EMAIL_APP_PASSWORD  - the 16-character Gmail App Password (not your real password)
#   EMAIL_TO            - address to send the digest to (can be the same as EMAIL_ADDRESS)

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587


def send_article_email(title, post_text, link):
    sender = os.environ.get("EMAIL_ADDRESS")
    password = os.environ.get("EMAIL_APP_PASSWORD")
    recipient = os.environ.get("EMAIL_TO")

    subject = f"AI News: {title}"
    body = f"{post_text}\n\nRead more: {link}"

    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient

    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
        server.starttls()
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())


if __name__ == "__main__":
    # manual test
    send_article_email(
        title="Test Article",
        post_text="This is a test post generated by the pipeline.",
        link="https://example.com"
    )
    print("Test email sent.")